- .github/workflows/continuous-integration-terraform.yml
- .github/workflows/continuous-integration-tfsec.yml
* Checks the terraform code using init, validate and fmt
* Uses the tfsec GitHub action to scan the code for potential security issues
> Add terraform ci workflows

- README.md
- locals.tf
- resource_group.tf
- variables.tf
* Creates a resource group that will contain the infrastructure resources
> Add resource group

- README.md
- locals.tf
- variables.tf
- virtual-network.tf
* Creates a virtual network
* Creates a subnet for the container app infrastructure
> Add virtual network

- README.md
- container-app.tf
- locals.tf
- variables.tf
* Creates a log analytics workspace
* Creates a Container App Environment within the virtual network
* Creates a Container App within the environment
> Add Container App

- README.md
- locals.tf
- mssql.tf
- variables.tf
- virtual-network.tf
* Creates an SQL server/database, with a private endpoint within the virtual network
* Creates a subnet for Container Instances, to allow launching a container to access the SQL database
> Conditionally launch Azure SQL

- README.md
- container-app.tf
- container-registry.tf
- locals.tf
- mssql.tf
- resource_group.tf
- variables.tf
- virtual-network.tf
* Allows specifying a map of tags to be applied to all resources
> Add tags to resources

- README.md
- container-app.tf
- container-registry.tf
- data.tf
- locals.tf
- mssql.tf
- resource_group.tf
- variables.tf
- virtual-network.tf
* Allows launching resources into an exiting resource group
* Allows using an existing VNet. The resource group must also be specified
> Allow specifying existing resource group and VNet

- container-app.tf
- redis-cache.tf
* The firewall requires the IPs of the container app, not the container app environment
> Fix redis firewall IPs

- README.md
- data.tf
- locals.tf
- script/apply-tags-to-container-app-env-mc-resource-group
- tagging.tf
* The managed resource group created with the container app environment does not include the tags specified
* This adds the tags once it has been created
> Apply tags to container env MC resorce group

- README.md
- dns.tf
- locals.tf
- variables.tf
* Allows creating a DNS zone, which will be later used to create records pointing to a CDN endpoint.
* Also allows specifying an SOA record
> Conditionally create DNS zone

- cdn.tf
* The `for_each` condition results are the wrong way round.
* The `cdn_frontdoor_custom_domain_ids` need to be referenced with a `for` loop
> Fix: CDN FrontDoor domain creation

- README.md
- cdn.tf
- locals.tf
- variables.tf
* Allows providing a list of response headers to add to a repsonse at the CDN Front Door
> Conditionally add response headers

- README.md
- cdn.tf
- locals.tf
- variables.tf
* Conditionally remove a list of response headers at the CDN Front Door
> Remove CDN response headers

- locals.tf
* Append the new `ruleset_add_response_headers_id` and `ruleset_remove_response_headers_id` ids to the ruleset list
> Fix `ruleset_ids` list

- cdn.tf
> Fix remove response header rule

- README.md
- locals.tf
- network-watcher.tf
- variables.tf
* location and resource group name are the wrong way round for the nsg flow logs resource.
* Fixes the nsg id list
* Adds the variables to the readme example.
> Fix network watcher

- monitor.tf
- https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/issues/67
> Fixes azurerm_monitor_action_group short name

- README.md
> Version bump v0.13.1

- README.md
- cdn.tf
- locals.tf
- variables.tf
* Allows enabling and configuring the CDN health probe interval and path
> Conditionally enable CDN health probe

- README.md
- locals.tf
- monitor.tf
> Fix deployment of worker alarm rules

- README.md
> Version bump v0.13.2

- monitor.tf
- added `to_set` to resolve `Invalid for_each argument...` when worker is not enabled
> Add to_set to for_each condition

- README.md
- container-app.tf
- locals.tf
- storage.tf
- variables.tf
- virtual-network.tf
Deploy Storage account for use by Container apps
> Conditional Storage Account

- README.md
- container-app.tf
- locals.tf
- variables.tf
* Adds the ability to scale manually through Terraform
> Allow configuring worker container min/max replicas

- mssql.tf
* Vulnerability assessment can discover, track, and help you remediate potential database vulnerabilities.
> Enable mssql threat detection

- README.md
- outputs.tf
Added basic descriptions to the outputs and also included the Event Hub and Log Analytics workspace so they can be referenced outside of this module
> Additional outputs

- README.md
- redis-cache.tf
* Adds some more logging for the Redis cache
> Add Redis diagnostic setting

- README.md
I have commented-out any variables that either have sensible defaults or are optional which leaves the remaining variables as ones I would consider as the "minimum" setup
> Update to Usage guide

- README.md
- cdn.tf
- locals.tf
- variables.tf
housekeeping update to make the port values overridable via variables
> Optionally override CDN Origin port numbers

- README.md
- locals.tf
- logging.tf
- variables.tf
`ContainerLog` is not a valid table name
> specify table names to export from log analytics workspace

- locals.tf
- postgres.tf
https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/pull/216
>  Merge ryantk:postgres-depends-on into main

- container-app.tf
> fix: Invalid type for "internal" in subnet properties

- README.md
- locals.tf
- outputs.tf
- Adds fqdn as output for the module
- Also slightly refactors the fqdn retrieval/usage in the `locals.tf` file
> feat: Output fqdn

- virtual-network.tf
* These are required for the Redis cache Private endpoint
> Add Redis cache VNet privat endpoint subnet and DNS Private Link

- monitor.tf
This change is for the Log Query Alerts that we have set up to track Exceptions from App Insights.
**Changes**
* Querying for requests that have a `5xx` status code, then joining the exception data that is related to it means we have a more thorough picture of the problem
* A link to App Insights transaction report is dynamically built using data available in the logs
* reduced the amount of information included in the log query as it is unnecessary
> Include app insights and request information in alerts

- .terraform.lock.hcl
- README.md
- locals.tf
- mssql.tf
- variables.tf
**SQL servers should have vulnerability assessment configured**
Vulnerability assessment can discover, track, and help you remediate potential database vulnerabilities.
**Severity**
High
> Enable MS SQL Vulnerability assessment

- README.md
- storage.tf
```
Message="The resource type 'microsoft.storage/storageaccounts/blobservices/containers' does not support diagnostic settings."
```
> Remove storage container 'blob' diagnostic setting

- README.md
- identity.tf
- locals.tf
- mssql.tf
- variables.tf
Fixes #319 by deploying a UAMI (with optional role assignment)
> Create a User Assigned Managed Identity for SQL server

- monitor.tf
* Microsoft agent suggested we switch to this aggregation to hopefully avoid false positives
> Switch to using Minimum metric alert aggregation

- cdn.tf
* Instead of using Regex we can use Any which will match either domain in the association
> Apply rate limit policy on any request uri

- locals.tf
- monitor.tf
* Dynamically set criteria based on Container App resource setting
* Increased severity of HTTP alarm to 'Critical'
* Made adjustments to other severities of alarms
> Deploy monitors for all container apps

- cdn.tf
* Optional CDN Redirect Ruleset for redirecting .well-known/security.txt and thanks.txt to a separate centralised domain.
* See https://github.com/DFE-Digital/vulnerability-disclosure-program
> Vulnerability Disclosure Program redirects

- monitor.tf
* This means we can standardise on how the alert is received by the Action Groups
> Normalise the dimensions raised by Exception and Log Alerts

- README.md
- mssql.tf
- versions.tf
* This feature is now supported in the AzureRM resource
> Remove azapi fix for MSSQL vulnerability assignment

- README.md
- function-app.tf
* Merging the health api function app in with the custom function apps for the diagnostic settings isn't possible as they are 2 seperate resources
> Fix function apps
