container-registry.tf

* If `environment` or `project_name` contain hyphens, some resources won't launch

Strip hyphens from some resource names

---

README.md
locals.tf
redis-cache.tf
variables.tf

* Redis cache defaults to version 4, which is mostly out of date.

Allow specifying Redis Cache version

---

README.md
cdn.tf
locals.tf
variables.tf

* Allows specifying a list of hostname redirects
* If the destination domain is pointing towards the CDN, it must be listed in the `cdn_frontdoor_custom_domains`, and have the TLS cert validated
* Provided in the format of `[{"from" = "example.com", "to" = "www.example.com"}]`

Conditionally add CDN host redirects

---

cdn.tf

* We should disable caching by default, then consider adding a feature to conditionally add cache settings
* https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/issues/46

Disable caching by default

---

README.md
dns.tf
locals.tf

* Even though the DNS zone has been specified in the custom domain, the TXT record still needs to be added for it to complete validation automatically. It appears that adding the DNS zone to the custom domain, just gives you the option to click a button to automatically create the record through the Azure Portal

Fix CDN certification validation

---

README.md
cdn.tf
html/waf-response.html
locals.tf
variables.tf

* Conditionally enable CDN Front Door rate limiting
* Creates a waf, which will be reused for future WAF rules
* Defaults to 300 request/min
* Allows providing a list of IPs to bypass the rate limiting

CDN Front Door Rate Limiting

---

README.md
locals.tf
network-watcher.tf
variables.tf

* Allows creating a Network Watcher, with Network Security Group Flow Logs
* Currently the only NSG is for the Container App. Any further ones created, can be added to the list `network_security_group_ids` in locals, which will then create a flow log for that too
* Allows conditionally enabling Traffic Analytics

Conditionally enable Network Watcher NSG flow logs

---

README.md
locals.tf
monitor.tf
variables.tf

**Add**
- Add latency monitor for Azure Front Door
**Fix**
- Correctly sets severity of existing alerts
**Changes**
- Removes the word "container" from the App Insights instance as it's not contextually correct

Revise Alert Rules for App Insights

---

container-app.tf

Fixes #79 
>[Microsoft.App/ContainerApps](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2022-03-01/containerapps?pivots=deployment-language-terraform#configuration-2):-
`ActiveRevisionsMode` controls how active revisions are handled for the Container app:
>
>Multiple: multiple revisions can be active.
>Single: Only one revision can be active at a time. Revision weights can not be used in this mode. If no value if provided, this is the default.

Switched revision mode to Multiple if min replicas > 1

---

monitor.tf

By default, the Web Test resource is deployed but not actively monitoring. Setting `enabled` to `true` ensures metrics get recorded into App Insights

Ensure web test is enabled

---

container-app.tf
monitor.tf

- Add the App Insights `InstrumentationKey` and `ConnectionString` into the Container Secrets and Environment variables for digestion by dotnet apps.
- Adds the `hidden-link` tag to the Web Test to retain the link to App Insights

Automatically include App Insights Connection

---

locals.tf

* `concurrentRequests` must be a string. Using `tostring()` allows the input to remain as a number

Fix scale rule schema types

---

container-app.tf

Fixes deployment of Scale Rules issue:
```
--------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: ContainerAppInvalidPropertyValue
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "ContainerAppInvalidPropertyValue",
│     "message": "Property 'rules.name' has an invalid value 'Concurrent HTTP Requests'. A value must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character."
│   }
│ }
```

Scale rule names must be lowercase and cannot contain spaces

---

README.md
locals.tf
logic-app.tf
monitor.tf
schema/common-alert-schema.json
variables.tf
webhook/slack.json

- Conditionally deploy Logic App Workflow, and subscribe it to an Alert Group so that it can be triggered by Alert Rule notifications.
- Set up a HTTP Request action for the Workflow, which takes the payload from the Alert Rule defined in the [Common Alert Schema](https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-common-schema) and creates a rich-text Slack compatible payload to POST to a provided Slack Webhook.

Deploy Logic App workflow

---

container-app.tf

`minReplicas` for the Worker container default to `null` which means, because the Worker container has no ingress traffic or liveness probes, it will always scale to zero.
This change is a safety precaution to ensure the worker container always stays alive by setting the `minReplicas` to `1`.

set minReplicas to 1 to prevent a scale-down to 0

---

logic-app.tf

If `enable_monitoring` was set to `false`, both the trigger and action resources would still try to be created, but they depend on the Logic App Workflow being built, which would only happen if `enable_monitoring` is `true`, causing a break and an error during a `terraform apply` due to dependencies not being met.
This PR adds the same conditional check for the trigger and action

Only create workflow steps if monitoring is enabled

---

monitor.tf

The web hook resource is now conditionally deployed using `count` so the array index needs adding here.

Add missing index

---

container-app.tf
storage.tf

- Fixes issue wherein Storage Containers and SAS tokens try to get deployed despite `enable_container_app_blob_storage` being set to `false`
- Corrects fallback value from `null` to `""`, used in the environment vars, when Storage Account is not deployed

Patch storage.tf 

---

locals.tf
monitor.tf

> The "for_each" set includes values derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this resource.
> When working with unknown values in for_each, it's better to use a map value where the keys are defined statically in your configuration and
* This changes the `monitor_container_ids` from a set to a map, so that it can be ran for the first time

Fix monitor container ids

---

locals.tf
network-watcher.tf

> The "for_each" set includes values derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this resource.
> When working with unknown values in for_each, it's better to use a map value where the keys are defined statically in your configuration and where only the values contain apply-time results.
* This changes the `network_security_group_ids` from a set to a map, so that it can be ran for the first time

Fix network security group ids list

---

container-app.tf
locals.tf

* If the container app blob storage isn't enabled, the secret isn't generated. Container app secrets can't be empty.

Fix container app blob storage envar

---

mssql.tf

Storage Accounts cannot accept seperators in the resource names

Fix invalid resource name

---

README.md
logic-app.tf

Microsoft Defender for Cloud security recommendation.
**Policy**: Diagnostic logs in Logic Apps should be enabled
**Description**: To ensure you can recreate activity trails for investigation purposes when a security incident occurs or your network is compromised, enable logging. If your diagnostic logs aren't being sent to a Log Analytics workspace, Azure Storage account, or Azure Event Hub, ensure you've configured diagnostic settings to send platform metrics and platform logs to the relevant destinations. Learn more in Create diagnostic settings to send platform logs and metrics to different destinations.
**Severity**: Low

Added Diagnostic Setting for Logic Workflow

---

README.md
versions.tf

This was missed from the Dependabot PR earlier

Updated provider version for azurerm to 3.46.0

---

.github/workflows/build-push-and-deploy-to-environment.yml
README.md

* Builds a docker image, optionally from a given Dockerfile name and context
* Pushes the docker image to a given Azure Container Registry
* Creates a draft/prerelease Release on dev/staging, and a Release on prod
* Restarts the Container app
* Optionally run Cypress tests

Add reusable build/push/deploy GitHub workflow

---

README.md
logging.tf

Having a custom query pack allows engineers to store custom Log Analytics Queries in a centralised place within their Resource Group. 
This ensures the correct tagging policies are adhered to as well.

Added custom Log Analytics query pack

---

README.md
container-app.tf
locals.tf
variables.tf

Some apps respond better to a TCP liveness probe instead of a HTTPS GET probe due to app-specific connection restrictions.

Added option to specify the method for container liveness probe

---

monitor.tf

- Makes it easier to track requests to the health check endpoint that have originated from App Insights' HTTP Test

Set a custom HTTP Header for the HTTP check

---

locals.tf
mssql.tf
redis-cache.tf
storage.tf

This Pr fixes an `Invalid for_each argument` error with the IPv4 network rules for the MSSQL and Redis instances.
Additionally it now correctly includes the Container Apps subnet ID which was previously invalid.
Finally, it will now always include the Container App static IP address within the network ACL for the Blob Storage Account, in addition to the Private Link

Fixes for network access rules

---

monitor.tf

* This will help reduce noise in the alerts by basing the monitor check on the smallest value in the 5 minute range. With this change it will be easier to identify a consistently increased latency

Switch monitor aggregation to minimum

---

README.md
data.tf
locals.tf

- In commit fca604ae5ca185de5819e6d1f2432f57d4f912cf a change to the logic_app_receiver block in the monitor action group changed the trigger url of the Logic App Workflow to be dynamic based on whether the operator is supplying their own Logic App workflow resource or choosing to create one with the module.
- If operators chose to create the Logic app workflow using the module, the actual value that was set was invalid and only contained the base url of the workflow. This meant that any requests to the workflow would fail silenty.
- The trigger url must contain an authenticated token which is only possible if using the callback_url attribute of the HTTP Trigger.
- The callback_url attribute cannot be gotten from a data source so the fix is to load it using a AzApi request instead.

Use correct Logic App trigger url in logic_app_receiver

---

script/apply-tags-to-container-app-env-mc-resource-group

* Removes the unintentional 'print' for gsub (Printing this just outputs the exit code rather than applying it)

Don't print awk's gsub in tagging script

---

monitor.tf

**Issue:**
If `enable_monitoring` is set to `false` then the Action Group does not get deployed which means this metric alert cannot locate the resource reference.
**Fix:**
Add a conditional check that means the metric alert only gets created if monitoring is enabled

Add conditional check for exception metric

---

container-app.tf
data.tf

`resource_group.location` == `westeurope` which is a region SKU and not a valid name that we can use in the `data` object which breaks any resource that implements the object.
Changing this to the `location` property of the Container App Environment output returns `West Europe` which is more appropriate.

Fix location reference for geolocation lookup

---

README.md
container-app.tf
data.tf
monitor.tf

- Using the azurerm_extended_locations was invalid and did not do what was anticipated
- This change reverts back to using hardcoded location tags
See:
https://learn.microsoft.com/en-gb/previous-versions/azure/azure-monitor/app/monitor-web-app-availability#azure

Revert change to geo-location lookup

---

README.md
outputs.tf

To allow users to link the terraform created DNS zone with another DNS zone either manually or through terraform in another resource.

Add DNS Zone name servers as output

---

cdn.tf

- Azure Rules need to have a unique numeric ordering as they are evaluated sequentially
- Closes #213

Correctly define order of rules

---

README.md
locals.tf
variables.tf
virtual-network.tf

* This will add a security group rule, which allows inbound traffic from the provided list of IPs

Allow providing a list of IPs for container apps inbound traffic

---

README.md
cdn.tf
data.tf
locals.tf

- We can get the FQDN from the container app resource instead of querying for a data source

Remove unnecessary data source reference for container app fqdn

---

cdn.tf
logic-app.tf
network-watcher.tf
redis-cache.tf
storage.tf

`retention_policy` has been deprecated in favor of `azurerm_storage_management_policy` however, `retention_policy` is an optional value therefore, we can just remove it.

Remove diagnostic settings deprecation retention policy

---

redis-cache.tf

* A Redis cache can be launched within a VNet, but only for the Premium SKU.
* When the SKU is anything else, we want to add a Private Endpoint to allow resources within the VNet to privately connecto to the Redis Cache

Create Redis Private Endpoint when not external

---

.terraform.lock.hcl
README.md
container-app.tf
locals.tf
storage.tf
variables.tf

**What does this do?**
* Offers users the ability to deploy an Azure File Share and use it as a networked file system across their container app environment. (Similar to mounting EFS in AWS)
**Why do we need this?**
* The 'Complete' service wants to upload files from their web container and have them accessible from sidecar containers
**Misc changes**
* Generalised the access control rules
* Removed invalid private link block

Deploy File Shares into the Storage Account

---

.github/workflows/continuous-integration-tfsec.yml

There is a bug in tfsec, where it finds vulnerabilities, but just outputs 'Ignoring - change not part of the current PR' - Even though it is. This is causing the check to pass, when it should fail.
Adding `working_directory: ''` is a suggested fix
https://github.com/aquasecurity/tfsec-pr-commenter-action/issues/90#issuecomment-1370985675

Fix tfsec not reporting correctly

---

README.md
container-app.tf
locals.tf
variables.tf

Being able to supply a custom container app name is useful when the `image_name` is too long or references an external container registry. e.g. _ghcr.io/_`DFE-Digital/foo` this would make the container name be `<prefix>-DFE-Digital/foo-app` which doesn't follow naming conventions

Allow optional overrides of the container name

---

container-app.tf

When deploying the File Share mount, the Container App resource errors with:
```
Error: Code="ManagedEnvironmentStorageNotFound" Message="Storage s184d01-comp-storage not found under managed environment"
```
The reference in the volume mount needs to be the name of the `azurerm_container_app_environment_storage` resource, not the `azurerm_storage_share`

Fix: Incorrect reference to File Share

---

README.md
locals.tf
redis-cache.tf
variables.tf

This change allows users to override the default configuration options for Redis.
I have set the default vars to match what [Azure defines](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_cache#default-redis-configuration-values)
- [maxmemory_reserved](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_cache#maxmemory_reserved) - (Optional) Value in megabytes reserved for non-cache usage e.g. failover.
- [maxmemory_delta](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_cache#maxmemory_delta) - (Optional) The max-memory delta for this Redis instance.
- [maxmemory_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_cache#maxmemory_policy) - …

Enable overrides of default Redis configuration options

---

logic-app.tf
redis-cache.tf

Diagnostic retention settings are specified at the storage account management policy level instead now

Removed deprecated diagnostic retention

---

dns.tf

- If the AFD domain DNS record's TTL is higher than the AFD CDN Endpoint, there could be a moment in time when the DNS cache becomes invalid. This could cause resolution issues resulting in intermittent connectivity

Reduce TTL to match AFD endpoint

---

README.md
logging.tf

**Diagnostic logs in Event Hub should be enabled**
This enables you to recreate activity trails for investigation purposes when a security incident occurs or your network is compromised.
**Severity**
Low

Add Diagnostic Setting for Event Hub

---

mssql.tf

If we're enabling the Security Alert policy, then we ought to notify people when alerts happen. 
We're also creating a storage container to hold security logs so we ought to write security alerts to the same place for auditing reasons.

Notify and log SQL vulnerability assessment reports

---

README.md
app-insights.tf
container-app.tf
custom-container-apps.tf
locals.tf
monitor.tf
variables.tf

* I've extracted App Insights resources and associated monitors into it's own file
* You can now specify a custom retention period for App Insights specific data
* A new Log Analytics workspace is deployed, exclusively for App Insights, with the same retention period. The justification for this is so that we can segregate system logs such as diagnostic settings and container logs, away from report-centric data such as user requests and app telemetry
* App Insights has become an optionally deployable resource (defaults to deploying by default). This is to cater to teams that may already be leveraging an existing App Insights resource

App insights isolation

---

README.md
mssql.tf

**Storage accounts should restrict network access using virtual network rules**
Previously this Storage Account was permitting any access. Given that we are storing SQL diagnostic logs and vulnerability reports in it, we ought to default `deny` incoming requests unless they are Azure Services or come directly from the SQL Server

Restrict MSSQL Log storage to Azure Monitor + SQL Server services only

---

README.md
cdn.tf
logging.tf
logic-app.tf
mssql.tf
network-watcher.tf
redis-cache.tf
storage.tf

- We don't need to record any 'metric' type diagnostic settings because they are only useful if we were running deeper reports. We already have the data available to use in Azure Monitor, so we're ingesting log data unnecessarily
- Instead of specifying the types of log category, we can use the category group 'audit' to get the minimum required diagnostic logs
- I've added diagnostic settings for file shares in the storage account, and the mssql security log storage account

Update Diagnostic settings

---

locals.tf

* It needs to use the `concat` function rather than `merge` for lists

Fix `subresource_names` parameter in `private_endpoint_storage`

---

storage.tf

* The `resource_manager_id` is needed to expose the resource id (`id` is the URL of the storage container)

Fix storage diagnostic setting

---

README.md
variables.tf

* Azure is not great at monitoring exclusively for TLS expiry so we'd rather people use a different tool for it
* This alarm is also quite noisy because it checks every 15 mins, self-remediates, then re-opens again after another 15mins elapses.

Set TLS monitor deployment to false by default

---

README.md
container-app.tf
container-registry.tf
identity.tf
locals.tf
outputs.tf
variables.tf

Assign a Managed Identity to the Container App for authenticating with ACR
* The previous managed identity was set up incorrectly
* Adds the option to skip assigning the role, if the operator does not have the permission to assign roles
* This method of authenticating with ACR is documented as a [Registry best practice](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-best-practices#authentication-and-authorization)
* This method is [documented](https://learn.microsoft.com/en-us/azure/container-apps/managed-identity?tabs=portal%2Cdotnet#add-a-user-assigned-identity) for Container Apps

Fix: Container App Managed Identity

---

container-app.tf

* It is currently not possible to remove secrets from Container App definitions, and we can't set the value to null, so we should just set it to an abitrary string so it doesnt error (https://github.com/hashicorp/terraform-provider-azurerm/issues/21739)
* This is only necessary when the 'admin' credentials are disabled for the registry and I have included a check for using the managed identity to be sure the value will not be used

Set ACR password to abitrary string when admin credentials are disabled

---

custom-container-apps.tf

Using `length(each.value.identity) > 0 ? [1] : []` for the `for_each` was invalid because in the dynamic block I was referencing the value as if it was an object, but it was just the number `1` 🙃

Fix invalid iteration reference

---

README.md
container-app.tf

If the Log setting for the Container App environment is switched from Log Analytics to Azure Monitor, then we ought to ensure there is a destination configured for the logs by default.

Set diagnostic settings for Container App environments

---

container-app.tf

Issue #333 says [tflint] Lookup with 2 arguments is deprecated (terraform_deprecated_lookup) therefore, needs to be replaced with map[key] syntax which is the equivalent.

Fix [tflint] deprecated Lookup

---

locals.tf

We have noticed that the PostgreSQL subnet and the Storage subnet have the same CIDR address space so one of them needs to change to avoid collisions.
Changing the Storage range should have the least amount of impact to our consuming services, but will require a rebuild of the private endpoint network structure
Closes #354

Increment storage subnet to avoid network collisions

---

locals.tf
virtual-network.tf

If an operator is deploying both a File Share and a Blob Container onto the same Storage Account there is a bug that prevents the private endpoint from deploying.
Closes #352

Split File and Blob Private endpoint resources

---

README.md
container-app.tf
locals.tf
variables.tf

* These variables/conditions aren't needed, as the values are correctly overwritten with the `registry_server`, `registry_username`, `registry_password` and `image_name` variables, for both the location of the image, and the registry configuration for the container app resource.
* Because this would only be true if `enable_container_registry` - So this also switches around the conditions in locals, so that the variables overwrite the default ACR values, if the specific variable is set

Remove custom registry variables

---

container-app.tf

```hcl
│ Error: "name" must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character and cannot have '--'. The length must not be more than 32 characters
│   26:   name                         = "${local.resource_prefix_sha_short}-storage"
```
because we were using a sha1 hash, it could begin with a number which broke the validation.

Storage name must begin with a letter

---

cdn.tf
container-app.tf
logging.tf
logic-app.tf
mssql.tf
redis-cache.tf
storage.tf

- Not having the disabled metrics in the Diagnostic Setting resources were causing noise in the Terraform Plan output because the value was being omitted.
- All of the resources we deploy do not support the 'Dedicated' Log Table type so it needs removing in favour of the default 'AzureDiagnostics'

Metric defaults and Log table types

---

.terraform.lock.hcl
README.md
data.tf
locals.tf
versions.tf

In version 1.13.0 of the AzAPI Provider, they have changed how data responses are returned by `azapi_resource_action`. Now we no longer need to use `jsondecode`.
This change does mean we need to ensure we bump the provider dependency to >= 1.13.0 to avoid the data source breaking on installations where the version is below this.

Pin minimum AzApi version to 1.13.0

---

README.md
mssql.tf

* Without a lifecycle policy, security reports will continue to build up resulting in unnecessary retention and costs
DevOps Card #169509

Set lifecycle policy on SQL security reports

---

monitor.tf

* With the aggregation set to 'Minimum' we encountered a problem when a new replica gets deployed, the previous replica gets shutdown but the metric value still tracks the old replica therefore firing the alarm. This is a false positive and not indicative of a failure scenario
* The change to move to 'Average' was suggested as a fix from Microsoft as this will be the average value across a period of time irrelevant of how many replicas get deployed.
* Setting the threshold to the min_replicas value of the Container is more useful because this allows us to determine a container failure scenario more accurately

Fix container replica monitor aggregation

---

storage.tf

* Without this, Azure Container Apps environment (AKS) cannot mount the File Share
* https://learn.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-linux?tabs=Ubuntu%2Csmb311
* https://github.com/microsoft/azure-container-apps/issues/852

Add support for NTLMv2

---

README.md
locals.tf
mssql.tf
network-watcher.tf
storage.tf
variables.tf

- Adds ability to set expiration period for SAS tokens on the storage accounts
I've used 2 days as the default value, as that's what the default Azure value is as far as i can tell.

feat(storage): Add SAS token expiration period configuration

---

locals.tf

* No need to deploy the Blob endpoint and pay for it, if the container is never deployed
* Closes https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/issues/402

[Fix] Storage Blob Private Endpoint

---

README.md
app-configuration.tf
container-app.tf
locals.tf
variables.tf
virtual-network.tf

Allow operators to deploy an App Configuration resource for centrally managing app settings and feature flags that are not intended to be managed by terraform.
https://learn.microsoft.com/en-us/azure/azure-app-configuration/overview
https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-container-apps?tabs=azure-portal#connect-azure-app-configuration-to-the-container-app
Closes https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/issues/403

[Feature] Deploy App Configuration

---

.terraform.lock.hcl
README.md
app-configuration.tf
container-app.tf
container-registry.tf
locals.tf
mssql.tf
network-watcher.tf
redis-cache.tf
storage.tf
variables.tf
versions.tf
virtual-network.tf

There are a number of deprecations and property differences between v3 and v4, but there are no backwards breaking changes that would warrant a major release on our side
**Important changes**
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#specifying-subscription-id-is-now-mandatory

Update to AzureRM Provider v4

---

container-app.tf
identity.tf
locals.tf

When we originally deployed the UAMI, it was because we were only using it to pull images from ACR. Now the UAMI is used for lots of other things so the two resources should be uncoupled.

[Identity] Container App Identity is now unlinked from ACR

---

locals.tf

Microsoft packages can only inherit the use of a System Assigned Managed Identity automatically. In our use case, we register a User Assigned Managed Identity. To expose this to the running app, we can set an environment variable

Add Identity client Id to env vars

---

container-app.tf

The `identity` block can only have 1, so we assign multiple IDs in the nested property

Fix: Invalid list reference

---

monitor.tf

- In Azure, the Database is used for scoping the alert, but it is often represented in the format `<server>/<database>` so i've updated the Alert to match

SQL server names missing from monitors

---

monitor.tf

* Having `/` in the resource name breaks Azure API requests because / is a URL escape character

Remove / char from resource name

---

README.md
locals.tf

When `local.enable_container_app_uami` is `false`, then `local.container_app_uami` is set as `null`. Consequently, `container_app_identity_ids` ends up having a null value in it.
This is not allowed by the TF provider, assumedly because you can't set a null identity.
- Add a null check to `local.container_app_uami` before adding to `local.container_app_identity_ids`
- Created a `local.container_app_client_id_value` variable. This i set as:
1. `azurerm_user_assigned_identity.containerapp[0].client_id` if `local.enable_container_app_uami` is `true`
2. Otherwise, if `var.container_app_identities` has exactly one identity in it, then that value is used
3. Otherwise, null
- Change the value of `AZURE_CLIENT_ID` in the container app environment variables (`local.container_app_env_vars`) to …

fix: Handle container_app_uami being null

---

locals.tf

Reverts a previous change where `var.container_app_identities` would be used for `AZURE_CLIENT_ID` on the container app under certain conditions.
Completely missed the fact that:
- `var.container_app_identities` takes the Azure resource ID (e.g. `/subscriptions/.....`
- but `AZURE_CLIENT_ID` needs, well, the managed identity client ID
I debated making this a new variable and setting it that way, but IMO leaving it like this means that it is easy to just set `AZURE_CLIENT_ID` yourself, to whatever value you want, by adding it to `var.container_environment_variables`.

fix(mi): revert client id change

---

locals.tf

Make `local.container_app_uami` reference the parent object so we can pull relevant properties out of it

Use Client ID in env vars + Resource ID in Identity map

---

README.md
locals.tf
monitor.tf
variables.tf

- For auditing purposes one might find it beneficial to enable Alert Rules that fire when an Administrative task starts in Azure.
- Setting var.alarm_for_delete_events to true will conditionally deploy a number of alert rules for services that are launched by Terraform

Alert Rules for deletion activities

---

README.md
versions.tf

~> | Allows only the right-most version component to increment. 
Examples: `~> 1.0`: Allows Terraform to install 1.1 and 1.2.1 but not 2.0.

Stabilised version constraints

---

monitor.tf

The deletion monitors rely on the action group being created which only happens if 'enable_monitoring' is true

Fix missing index reference for action group

---

README.md
locals.tf
monitor.tf
variables.tf

Adds an new log query alert for App Insights so that we can toggle-on monitoring for Traces where the severity level is Error or greater, but including a second optional toggle for including Warnings too (they are especially noisy sometimes). This can be useful for developers for raising visibility of non-exception errors.

[145886] Alert on error logs

---

functions/src/health-api/function_app.py

* 'success' column was being interpreted as a string '0' and always being displayed by the Function App as boolean 'true' which is not indicative of the status. This change ensures the data queried in KQL is cast as a boolean early to normalise the data type

Cast type to boolean

---

locals.tf
network-watcher.tf

>On 30 September 2027, Network security group (NSG) flow logs in Azure Network Watcher will be retired. As part of this retirement, you'll no longer be able to create new NSG flow logs starting 30 June 2025. To avoid service disruptions, migrate to virtual network flow logs by 30 September 2027

Migrate scope from NSG to VNET

---

monitor.tf

* The metric alert commonly alarms during a container replica provisioning event which causes false positives due to the emitter not having any data for the new replica. Switching to a dynamic criteria means it will test against a common sliding average value across all replicas. Therefore container replica provisioning will be less likely to trigger the alarm
**Before:**
**After:**

Switch to dynamic criteria for replica count alarm

---

cdn.tf

* Fixes invalid plan due to default value of '30' being introduced into the provider. When the SKU of the CDN is 'Standard', the JS Challenge property is not permitted to be set so we set it to 'null'

Set default js challenge property

---

README.md
locals.tf
variables.tf
virtual-network.tf

* Provides people with the option to blackhole all outgoing traffic. Useful when your subnets are expected to only connect over Private Endpoints and not to any external services

Deny all egress within the VNET

---

README.md
outputs.tf

This can be useful if setting up DNS outside of this module

Register inbound IP of container app env as terraform output

---

signalr.tf

* When deploying into an existing resource group, the local variable needs to be used

SignalR resource group fix
